---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```


```{r}
players <- read_csv("players.csv")

```

```{r}
glimpse(players)
```




```{r}
view(players)
```

```{r}
players1 <- players
```


```{r}
players1 %>%
  ggplot(aes(x = overall)) +
  geom_histogram(col = "white")
```

```{r}
players1 %>%
  ggplot(aes(y = overall)) +
  geom_boxplot() +
  coord_flip()
```
```{r}
getMode <- function(data){
  tabled_data <- table(data)
  table_names <- names(tabled_data)
  return( table_names[tabled_data == max(tabled_data)] )
}
```


```{r}
library(prob)
players1 %>%
  summarise(
    mean_overall = mean(overall),
    median_overall = median(overall),
    mode_overall = getMode(overall)
  )
```

```{r}
overall_outliers <- players %>%
  select(overall) %>%
  arrange(desc(overall))
overall_outliers
```

```{r}
players1 %>%
  summarise(
     min = range(overall)[1],
    max = range(overall)[2],
    range = max - min
  )
```

```{r}
players1 %>%
  summarise(
    Q1 = quantile(overall, 0.25),
    Q2 = quantile(overall, 0.5),
    Q3 = quantile(overall, 0.75),
    IQR = Q3 - Q1
  )
```

```{r}
players1 %>%
  summarise(IQR = IQR(overall))
```


```{r}
players1 %>%
  summarise(
    sd = sd(overall)
  )
```







```{r}
players1 %>%
  ggplot(aes(x = crossing, y = overall)) +
  geom_point()
```
```{r}
players1 %>%
  summarise(r = cor(crossing, overall))
```




```{r}
players1 %>%
  ggplot(aes(x = finishing, y = overall)) +
  geom_point()
```
```{r}
players1 %>%
  summarise(r = cor(finishing, overall))
```






```{r}
players1 %>%
  ggplot(aes(x = dribbling, y = overall)) +
  geom_point()
```

```{r}
players1 %>%
  summarise(r = cor(dribbling, overall))
```






```{r}
players1 %>%
  ggplot(aes(x = agility, y = overall)) +
  geom_point()
```

```{r}
players1 %>%
  summarise(r = cor(agility, overall))
```







```{r}
players1 %>%
  ggplot(aes(x = shot_power, y = overall)) +
  geom_point()
```

```{r}
players1 %>%
  summarise(r = cor(shot_power, overall))
```




```{r}
players1 %>%
  ggplot(aes(x = aggression, y = overall)) +
  geom_point()
```

```{r}
players1 %>%
  summarise(r = cor(aggression, overall))
```







```{r}
players1 %>%
  ggplot(aes(x = composure, y = overall)) +
  geom_point()
```

```{r}
players1 %>%
  summarise(r = cor(composure, overall))
```

```{r}
players1 %>%
  summarise(r_crossing = cor(crossing, overall),
            r_finishing = cor(finishing, overall),
            r_dribbling = cor(dribbling, overall),
            r_agility = cor(agility, overall),
            r_shotpower = cor(shot_power, overall),
            r_aggression = cor(aggression, overall),
            r_composure = cor(composure, overall))
```




```{r}
players1 %>%
  ggplot(aes(x = composure, y = overall)) +
  geom_point() +
  geom_point(aes(x = mean(composure), y = mean(overall)), col = "red", size = 5)
```

```{r}
composure_model <- lm(formula = players1$overall ~ players1$composure)

composure_model
  
```

```{r}
summary(composure_model)
```




```{r}
library(modelr)
```




```{r}
line <- function(x, b0, b1){
  return(b0 + x * b1)
}
```


```{r}
players1 <- players1 %>%
  mutate(fit_overall = line(composure, b0 = 39.8044, b1 = 0.4474))
```


```{r}
players1_plot <- players1 %>%
  ggplot(aes(x = composure, y = overall)) +
  geom_point() +
  geom_point(aes(y = fit_overall), shape = 1) +
  geom_abline(slope = 0.4474, intercept = 39.8044, col = "red") +
  geom_segment(aes(xend = composure, yend = fit_overall), alpha = 0.5)
players1_plot
```





```{r}
players1 <- players1 %>%
  mutate(residual = overall - fit_overall)
players1
```

```{r}
players1 <- players1 %>%
  mutate(sq_residual = residual^2)
players1
```

```{r}
players1 %>%
  summarise(sum_sq_residuals = sum(sq_residual))
```








```{r}
players1 %>%
select(composure, overall, fit_overall, residual, sq_residual) %>%
  add_predictions(composure_model) %>%
  add_residuals(composure_model) %>%
  ggplot(aes(x = composure)) +
  geom_point(aes(y = overall)) +
  geom_line(aes(y = pred), col = "red")
```




```{r}
players1 %>%
  ggplot(aes(x = composure, y = overall)) +
  geom_point() +
  geom_abline(
    intercept = composure_model$coefficients[1],
    slope = composure_model$coefficients[2],
    col = "red"
  )
```
```{r}
library(broom)
```



```{r}
tidy_output <- clean_names(tidy(composure_model))
tidy_output
```


```{r}
glance_output <- clean_names(glance(composure_model))
glance_output
```

```{r}
glance_output$r_squared
```




```{r}
composure_predict <- players1 %>%
  mutate(composure_plus5 = composure + 5)
```


```{r}
composure_predict %>%
  select(composure_plus5, overall) %>%
  add_predictions(composure_model) %>%
  ggplot(aes(x = composure_plus5)) +
  geom_point(aes(y = overall)) +
  geom_line(aes(y = pred), col = "red")
```

```{r}
mean_composure <- players1 %>%
  summarise(mean(composure))
mean_composure
```



```{r}
mean_composure_plus5 <- composure_predict %>%
  summarise(mean(composure_plus5))
mean_composure_plus5
```





```{r}
composure_plus5_model <- lm(overall ~ composure_plus5, data = composure_predict)
summary(composure_plus5_model)
```

```{r}
tidy_output_predict <- clean_names(tidy(composure_plus5_model))
tidy_output_predict
```

```{r}
glance_output_predict <- clean_names(glance(composure_plus5_model))
glance_output_predict
```

```{r}
library(ggfortify)
autoplot(composure_model)
```

```{r}
autoplot(composure_plus5_model)
```


```{r}
bootstrap_distribution_slope <- players1 %>%
  specify(formula = overall ~ composure) %>%
  generate(reps = 10000, type = "bootstrap") %>%
  calculate(stat = "slope")

slope_ci95 <- bootstrap_distribution_slope %>%
  get_ci(level = 0.95, type = "percentile")
slope_ci95
```


```{r}
bootstrap_distribution_slope %>%
  visualise(bins = 30) +
  shade_ci(endpoints = slope_ci95)
```


```{r}
clean_names(tidy(composure_model, conf.int = TRUE, conf.level = 0.95))
```







```{r}
international_param <- players %>%
  mutate(sig_int_rep = international_reputation > 1) %>%
  summarise(prop_int_rep = mean(sig_int_rep))
international_param
```


```{r}
prop_plot <- players %>%
  mutate(sig_int_rep = international_reputation > 1) %>%
  ggplot(aes(x = sig_int_rep)) +
  geom_bar()
prop_plot
```







