---
title: "R Notebook"
output: html_notebook
---

```{r}
stock_prices <- c(23, 27, 23, 21, 34, 24, 25, 30, 37, 30)
```

```{r}
day_of_week <- rep(c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), times = 2, ordered = TRUE)
day_of_week

```
```{r}
day_of_week_factor <- factor(day_of_week, ordered = TRUE)
day_of_week_factor
class(day_of_week_factor)
class(day_of_week)
```
```{r}
named_stock_prices <- names(stock_prices)
```
```{r}
named_stock_prices <- stock_prices
named_stock_prices
```
```{r}
names(named_stock_prices) <- day_of_week_factor
```

```{r}
named_stock_prices[c(day_of_week)]
```

```{r}
stock_data <- data.frame(stock_prices, day_of_week)
View(stock_data)
```
```{r}
stock_list <- list(stock_prices = "Prices", day_of_week = "Day", stock_data = "Data")
stock_list
```
```{r}
stock_prices[[4]]
```
```{r}
stock_prices[[5]]
```

```{r}
stock_prices[[6]]
```
```{r}
stock_prices[c(4,5,6)]
```
```{r}
stock_data[ ,2]
```
```{r}
stock_data[ ,1]
```

```{r}
stock_data[3, ]
```
```{r}
stock_data[1,3]
```
```{r}
subset(stock_data, stock_prices>30)
```
```{r}
stock_list["stock_data"]
```














