---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```

```{r}
ames <- read_csv("ames.csv")
```

```{r}
ames <- clean_names(ames)
glimpse(ames)
```


```{r}
ames %>%
  ggplot(aes(x = lot_area)) +
  geom_histogram(col = "white")
```

```{r}
pop_param <- ames %>%
  summarise(mean_lot_area = mean(lot_area))
pop_param
```

```{r}
rep_sample_200 <- ames %>%
  rep_sample_n(size = 100, reps = 1000) %>%
  group_by(replicate) %>%
  summarise(
    mean_lot_area = mean(lot_area)
  ) 

rep_sample_200 %>%
  ggplot(aes(x = mean_lot_area)) +
  geom_histogram(col = "white")
```

```{r}
single_sample_100 <- ames %>%
  rep_sample_n(size = 100, reps = 1) %>%
    ungroup() %>%
    select(lot_area)
```


```{r}
bootstrap_rep_sample_100 <- single_sample_100 %>%
  specify(response = lot_area) %>%
    generate(reps = 1000, type = "bootstrap") %>%
    calculate(stat = "mean")
  
```

```{r}
bootstrap_lot_area_ci <- bootstrap_rep_sample_100 %>%
  get_confidence_interval(level = 0.95, type = "percentile")
bootstrap_lot_area_ci
  
```


```{r}
bootstrap_rep_sample_100 %>%
  visualise(bins = 30) +
  shade_confidence_interval(endpoints = bootstrap_lot_area_ci)
```


```{r}
bootstrap_lot_area_ci99 <- bootstrap_rep_sample_100 %>%
  get_confidence_interval(level = 0.99, type = "percentile")
bootstrap_lot_area_ci99
```

```{r}
bootstrap_rep_sample_100 %>%
  visualise(bins = 30) +
  shade_confidence_interval(endpoints = bootstrap_lot_area_ci99)
```

```{r}
bootstrap_rep_sample_100 %>%
  summarise(point_est = mean(stat))
bootstrap_rep_sample_100

```

For comparison:


```{r}
single_sample_100 %>%
  summarise(mean(lot_area))
```

```{r}
pop_param <- ames %>%
  summarise(mean_lot_area = mean(lot_area))
pop_param
```






Extension



```{r}
ames_before_1920 <- ames %>%
mutate(before_1920 = as.numeric(year_built < 1920))
ames_before_1920
```

```{r}
single_sample_200 <- ames_before_1920 %>%
  rep_sample_n(size = 200, reps = 1) %>%
  ungroup() %>%
  select(before_1920) %>%
  mutate(before_1920 = as.character(before_1920))
```


```{r}
bootstrap_rep_sample <- single_sample_200 %>%
  specify(response = before_1920, success = "1") %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "prop")
```

I don't know why that's red now!  I came back to try more reps, but it was taking too long, so I went back to 5,000, but now it's not happy.  I can't see an explanation or an error.  Maybe it's still thinking.


```{r}
bootstrap_prop_ci <- bootstrap_rep_sample %>%
  get_confidence_interval(level = 0.95, type = "percentile")
bootstrap_prop_ci
```

```{r}
bootstrap_rep_sample %>%
  visualise(bins = 30) +
  shade_confidence_interval(endpoints = bootstrap_prop_ci)
```

```{r}
single_sample_200 %>%
  summarise(point_est = mean(before_1920 == "1"))
```

```{r}
bootstrap_rep_sample %>%
  summarise(point_est = mean(stat))
```










